@reservation=http://localhost:3000
@auth=http://localhost:3001
###
GET {{reservation}}
###
POST {{reservation}}/reservations
Content-Type: application/json

{
  "startDate":"12/20/2022",
  "endDate":"12/22/2022",
  "placeId":"12345",
  "invoiceId":"493"
}
###
GET {{reservation}}/reservations
###
GET {{reservation}}/reservations/6552b7e004d3531dfd9fdd20
###
DELETE {{reservation}}/reservations/6552b730151d894ae9179de5
###
POST {{auth}}/users
Content-Type: application/json

{
  "email":"lorentsh@gmail.com",
  "password":"Qwer1234."
}
###
POST {{auth}}/login
Content-Type: application/json

{
  "email":"lorentsh@gmail.com",
  "password":"Qwer1234."
}